host=[YOUR_ADDRESS]
adminPort=[YOUR_PORT_TO_HTTP]
workerPort=[YOUR_PORT_TO_WS]
baseDir=[YOUR_DIR_TO_USE]

enableRegistry=true
allowPullNonPermit=true
allowPullAnonymous=true

allowNonUser=true
enforceJwtAuth=false
useWorkerMtls=false
useAdminTls=false

redisAddress=[YOUR_REDIS_ADDRESS]
redisPort=[YOUR_REDIS_PORT]
redisPassword=[YOUR_REDIS_PASSWORD]
redisUseSSL=false
redisDatabaseNum=0